version: "3.9"
services:
    coodinator:
        image: trino:latest
        volumes:
          - ./coordinator-etc:/trino-etc
        networks:
          - trino-net
        hostname: coordinator
        ports:
          - "8080:8080"
    worker1:
        image: trino:latest
        volumes:
          - ./worker-etc:/trino-etc
        networks:
          - trino-net
        hostname: worker1
    worker2:
        image: trino:latest
        volumes:
          - ./worker-etc:/trino-etc
        networks:
          - trino-net
        hostname: worker2
    postgresql:
        image: postgres:14.1
        networks:
          - trino-net
        hostname: postgresql
        restart: always
        environment:
            POSTGRES_PASSWORD: my-secret-pw
            POSTGRES_USER: yulin
    mysql:
        image: mysql:8.0.27
        networks:
          - trino-net
        hostname: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw


networks:
    trino-net:
        driver: bridge
