version: "3.9"
services:
    coodinator:
        image: trino:latest
        volumes:
          - ./coordinator-etc:/trino-etc
        networks:
          - trino-net
        hostname: coordinator
        ports:
          - "8080:8080"
    worker1:
        image: trino:latest
        volumes:
          - ./worker-etc:/trino-etc
        networks:
          - trino-net
    worker2:
        image: trino:latest
        volumes:
          - ./worker-etc:/trino-etc
        networks:
          - trino-net

networks:
    trino-net:
        driver: bridge
